const path=require('path')
// console.log(path.sep)
const pa=path.join('/content/','subfolder','test.txt')
// console.log(pa)
const base=path.basename(pa)
console.log(base)
const abs=path.resolve(__dirname,'content','subfolder','test.txt')
// console.log(abs) 
